version: '3.3'

services:
  web:
    image: "note_taking"
    container_name: "note_taking"
    build:
      context: ./project
    volumes:
      - ./project:/app
    ports:
      - 5000:5000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://root:root@postgres_db:5432/note_taking
      - OpenAI_API_KEY=$OpenAI_API_KEY
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgres_db"
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root